import type { Method } from '../types';

/** Focus / reprise : démarrer, tenir, redémarrer. Source V2, §6. */
export const focusMethods: Method[] = [
  {
    id: 'pomodoro',
    title: 'Pomodoro / Timeboxing',
    subtitle: 'Attention · Réglage',
    summary:
      'Un bloc de travail avec une sortie observable et le téléphone hors de portée. 25-5 pour démarrer ou fatigué, 45-10 ou 50-10 en base — c’est un réglage, pas une loi biologique.',
    categories: ['focus'],
    subjects: [],
    infoTypes: [],
    problems: ['concentration', 'demarrer', 'fatigue'],
    aliases: [
      'pomodoro',
      'timer',
      'minuteur',
      '25 5',
      '25/5',
      '50 10',
      '50/10',
      'bloc travail',
      'timeboxing',
      'sessions de travail',
    ],
    keywords: ['attention', 'blocs', 'pause', 'sortie observable'],
    tags: ['réglage'],
    whenToUse: [
      'Pour démarrer, limiter l’évitement ou structurer une tâche quand l’attention est faible.',
    ],
    avoid: [
      'Ce n’est pas une loi biologique : ne coupe pas artificiellement un raisonnement utile, et ne choisis pas le minuteur au lieu de travailler.',
    ],
    quickSteps: [
      'Définis une sortie observable.',
      'Choisis un bloc adapté : 25-5 pour démarrer ou fatigué, 45-10 / 50-10 en base, plus long si la tâche le permet.',
      'Téléphone hors de portée.',
      'Travaille jusqu’à la condition de fin ou la pause.',
      'Mesure la qualité, pas seulement le temps.',
    ],
    procedure: [
      { text: 'Définir une sortie observable.', detail: '« Restituer 3 mécanismes », « résoudre les exercices 1 à 4 » — pas « travailler la biochimie ».' },
      { text: 'Choisir un bloc adapté : 25-5 pour démarrer / fatigue, 45-10 ou 50-10 en base, plus long si la tâche le permet.' },
      { text: 'Téléphone hors de portée.' },
      { text: 'Travailler jusqu’à la condition de fin ou la pause.' },
      { text: 'Mesurer la qualité, pas seulement le temps.' },
    ],
    mastery: [
      'Le format aide à produire davantage sans fragmenter inutilement.',
    ],
    limits: [
      '« Pomodoro 25/5 obligatoire » est un mythe : la durée dépend de la tâche et de la fatigue.',
    ],
    example:
      'Sortie observable : « restituer les 3 voies du chapitre ». Bloc de 45 minutes, téléphone hors de la pièce, pause de 10 — et on juge le bloc à ce qui a été produit, pas au temps passé.',
    related: ['demarrage-10-minutes', 'friction-numerique', 'journee-minimale'],
    source: 'Source V2 — §6 Bibliothèque, p. 28-29',
  },
  {
    id: 'demarrage-10-minutes',
    title: 'Protocole de démarrage en 10 minutes',
    subtitle: 'SOS · Procrastination',
    summary:
      'Téléphone hors de la pièce, un seul support ouvert, une sortie écrite, 10 minutes lancées sans négocier. À 10 minutes : continue si engagé, sinon réduis encore l’unité.',
    categories: ['focus'],
    subjects: [],
    infoTypes: [],
    problems: ['demarrer', 'concentration'],
    aliases: [
      'sos démarrer',
      'procrastination',
      '10 minutes',
      'j’arrive pas à commencer',
      'je n’arrive pas à commencer',
      'commencer à travailler',
      'me lancer',
      'me mettre au travail',
    ],
    keywords: ['démarrage', 'évitement', 'sortie observable', 'lancement'],
    tags: ['SOS'],
    whenToUse: [
      'Quand tu n’arrives pas à commencer ou que la tâche paraît trop grande.',
    ],
    avoid: [
      'N’utilise pas les 10 minutes pour choisir une nouvelle app, réorganiser le bureau ou planifier indéfiniment.',
    ],
    quickSteps: [
      'Téléphone hors de la pièce.',
      'Ouvre uniquement le support nécessaire.',
      'Écris une sortie : « restituer 3 mécanismes » ou « résoudre 1 à 4 ».',
      'Lance 10 minutes sans négocier la suite.',
      'À 10 minutes : continue si engagé ; sinon réduis encore l’unité.',
    ],
    procedure: [
      { text: 'Téléphone hors de la pièce.' },
      { text: 'Ouvrir uniquement le support nécessaire.' },
      { text: 'Écrire une sortie : « restituer 3 mécanismes » ou « résoudre 1 à 4 ».' },
      { text: 'Lancer 10 minutes sans négocier la suite.', detail: 'Le contrat porte sur 10 minutes, pas sur la journée : c’est ce qui le rend signable.' },
      { text: 'À 10 minutes : continuer si engagé ; sinon réduire encore l’unité.' },
    ],
    mastery: [
      'Tu passes de l’évitement à une production observable.',
    ],
    example:
      'Dimanche 14 h, aucune envie : téléphone dans l’entrée, poly de biocell seul sur le bureau, sortie écrite « restituer 3 mécanismes », minuteur 10 minutes. À 14 h 10, tu décides — en général, tu continues.',
    next: { id: 'pomodoro', label: 'Lancé·e ? Enchaîne sur un vrai bloc de travail.' },
    related: ['pomodoro', 'friction-numerique', 'journee-minimale'],
    source: 'Source V2 — §6 Bibliothèque, p. 29',
  },
  {
    id: 'friction-numerique',
    title: 'Réduction de friction numérique',
    subtitle: 'Focus · Environnement',
    summary:
      'Le levier n’est pas la volonté ni une « détox dopamine » : c’est la friction. Retire les signaux, éloigne le téléphone, prévois une fenêtre de consultation, prépare la première tâche la veille.',
    categories: ['focus'],
    subjects: [],
    infoTypes: [],
    problems: ['concentration', 'demarrer'],
    aliases: [
      'téléphone',
      'telephone',
      'scroll',
      'distraction',
      'notifications',
      'dopamine detox',
      'détox dopamine',
      'focus',
      'réseaux sociaux',
      'je suis distrait',
    ],
    keywords: ['environnement', 'friction', 'interruptions', 'signaux'],
    tags: ['environnement'],
    whenToUse: [
      'Quand le téléphone, les notifications ou le scroll interrompent les blocs.',
    ],
    avoid: [
      'Ne te raconte pas une « détox dopamine » : le levier est la friction et l’environnement.',
    ],
    quickSteps: [
      'Retire les signaux et notifications non essentiels.',
      'Mets le téléphone hors de la pièce.',
      'Prévois une fenêtre de consultation.',
      'Prépare la première tâche la veille.',
      'Utilise un seul minuteur.',
    ],
    procedure: [
      { text: 'Retirer les signaux et notifications non essentiels.' },
      { text: 'Mettre le téléphone hors de la pièce.', detail: 'Hors de portée ne suffit pas toujours : hors de la pièce supprime le coût de résistance.' },
      { text: 'Prévoir une fenêtre de consultation.' },
      { text: 'Préparer la première tâche la veille.' },
      { text: 'Utiliser un seul minuteur.' },
    ],
    mastery: [
      'Les ouvertures automatiques diminuent et les blocs se terminent davantage.',
    ],
    example:
      'Notifications coupées sauf appels, téléphone dans une autre pièce, fenêtre de consultation à 13 h et 19 h, le poly de demain déjà ouvert sur le bureau la veille.',
    related: ['pomodoro', 'demarrage-10-minutes'],
    source: 'Source V2 — §6 Bibliothèque, p. 29-30',
  },
  {
    id: 'journee-minimale',
    title: 'Journée minimale',
    subtitle: 'SOS · Fatigue · Continuité',
    summary:
      'Énergie très basse : protège sommeil et repas, fais l’entretien mémoire réellement dû, traite UN objet critique, une petite application, et prépare la première action de demain. Éviter le zéro, pas compenser.',
    categories: ['focus'],
    subjects: [],
    infoTypes: [],
    problems: ['fatigue', 'retard'],
    aliases: [
      'fatigué',
      'fatigue',
      'journée minimale',
      'petite journée',
      'j’ai plus d’énergie',
      'épuisé',
      'epuise',
      'mode minimum',
      'à plat',
    ],
    keywords: ['énergie', 'sommeil', 'continuité', 'reprise', 'récupération'],
    tags: ['SOS'],
    whenToUse: [
      'Quand l’énergie est très basse et qu’une journée normale serait irréaliste.',
    ],
    avoid: [
      'Ne transforme pas le mode minimum en norme permanente, et ne compense pas par une nuit blanche.',
    ],
    quickSteps: [
      'Protège sommeil, repas et récupération.',
      'Fais les éléments de mémoire réellement dus / essentiels.',
      'Traite un seul objet critique.',
      'Fais une petite application ou un QCM corrigé si possible.',
      'Prépare la première action du lendemain.',
    ],
    procedure: [
      { text: 'Protéger sommeil, repas et récupération.' },
      { text: 'Faire les éléments de mémoire réellement dus / essentiels.', detail: 'Les cartes dues essentielles, pas les nouvelles.' },
      { text: 'Traiter un seul objet critique.' },
      { text: 'Faire une petite application / QCM corrigée si possible.' },
      { text: 'Préparer la première action du lendemain.', detail: 'Une reprise préparée la veille coûte deux fois moins cher le matin.' },
    ],
    mastery: [
      'Tu évites le zéro et préserves la reprise sans aggraver la fatigue.',
    ],
    example:
      'Journée à plat : nuit protégée, cartes dues essentielles uniquement, un seul objet critique (le mécanisme qui bloque la suite), dix QCM corrigés, et le poly de demain préparé sur le bureau.',
    related: ['triage-retard', 'demarrage-10-minutes', 'revision-rapide'],
    source: 'Source V2 — §6 Bibliothèque, p. 30',
  },
  {
    id: 'triage-retard',
    title: 'Triage du retard 24-72 h',
    subtitle: 'SOS · Retard',
    summary:
      'Quand « je suis en retard » devient une sensation globale : liste les objets exacts, classe-les, suspends le non-essentiel, 2 priorités rouges max par jour, plan sur 3 jours seulement.',
    categories: ['focus', 'corriger'],
    subjects: [],
    infoTypes: [],
    problems: ['retard', 'anki-deborde', 'stress'],
    aliases: [
      'retard',
      'rattraper',
      'trop de cours',
      'je suis débordé',
      'je suis débordée',
      'deborde',
      'submergé',
      'saturé',
      'sature',
      'triage',
      'en retard sur le programme',
    ],
    keywords: ['priorités', 'classement', 'plan 3 jours', 'suspendre', 'charge'],
    tags: ['SOS'],
    whenToUse: [
      'Quand « je suis en retard » devient une sensation globale et paralysante.',
    ],
    avoid: [
      'Ne construis pas un plan punitif de plusieurs semaines et ne vole pas du sommeil.',
    ],
    quickSteps: [
      'Liste les objets exacts.',
      'Classe : bloque la suite / fortement évalué / entretien / supprimable.',
      'Suspends les nouvelles cartes non essentielles.',
      'Choisis au maximum deux priorités rouges par jour.',
      'Planifie seulement 3 jours.',
      'Fais un test diagnostique court.',
      'Réévalue.',
    ],
    procedure: [
      { text: 'Lister les objets exacts.', detail: 'Des objets nommés (« chapitre 4 de biochimie »), pas « tout mon retard ».' },
      { text: 'Classer : bloque la suite / fortement évalué / entretien / supprimable.' },
      { text: 'Suspendre les nouvelles cartes non essentielles.' },
      { text: 'Choisir au maximum deux priorités rouges par jour.' },
      { text: 'Planifier seulement 3 jours.', detail: 'Au-delà de 72 h, le plan devient une fiction qui culpabilise.' },
      { text: 'Faire un test diagnostique court.' },
      { text: 'Réévaluer.' },
    ],
    mastery: [
      'Le retard devient une liste fermable et la charge redevient soutenable.',
    ],
    example:
      '« Je suis noyé·e » devient : biochimie ch. 4 (bloque la suite), annales de biostats (fortement évalué), cartes dues (entretien), fiche de SHS recopiée (supprimable). Deux rouges par jour, plan sur 3 jours.',
    related: ['journee-minimale', 'revision-rapide', 'audit-deck', 'demarrage-10-minutes'],
    source: 'Source V2 — §6 Bibliothèque, p. 30-31',
  },
  {
    id: 'nrar-stress',
    title: 'N-R-A-R : stress aigu',
    subtitle: 'SOS · Stress',
    summary:
      'Quand le stress bloque l’action : Nommer (« le stress monte ; ce n’est pas une preuve que je ne sais rien ») → Respirer lentement 1-2 min → Ancrer → Reprendre la prochaine action simple.',
    categories: ['focus'],
    subjects: [],
    infoTypes: [],
    problems: ['stress'],
    aliases: [
      'stress',
      'panique',
      'nrar',
      'n-r-a-r',
      'je bloque examen',
      'je panique',
      'crise pendant qcm',
      'stress aigu',
      'anxiété examen',
    ],
    keywords: ['respiration', 'ancrage', 'reprise', 'blocage'],
    tags: ['SOS'],
    whenToUse: [
      'Quand le stress monte pendant un QCM, un exercice ou une session et bloque l’action.',
    ],
    avoid: [
      'Ce n’est pas un traitement d’une détresse persistante : si le fonctionnement se dégrade durablement, chercher une aide humaine / professionnelle.',
    ],
    quickSteps: [
      'Nomme : « le stress monte ; ce n’est pas une preuve que je ne sais rien ».',
      'Respire lentement 1 à 2 minutes, sans forcer.',
      'Ancre : pieds au sol, mâchoire et épaules relâchées, regarde les informations disponibles.',
      'Reprends : exécute la prochaine action simple, ou passe à une question accessible puis reviens.',
    ],
    procedure: [
      { text: 'Nommer : « le stress monte ; ce n’est pas une preuve que je ne sais rien ».' },
      { text: 'Respirer lentement 1 à 2 minutes sans forcer.' },
      { text: 'Ancrer : pieds au sol, relâcher mâchoire / épaules, regarder les informations disponibles.' },
      { text: 'Reprendre : exécuter la prochaine action simple ou passer à une question accessible puis revenir.' },
    ],
    mastery: [
      'Le protocole permet de reprendre une action utile sans ajouter une nouvelle spirale.',
    ],
    limits: [
      'Si le fonctionnement, le sommeil ou la sécurité se dégradent durablement, la bonne action est un soutien humain ou professionnel — pas une app.',
    ],
    example:
      'Question 17, trou noir complet : « le stress monte ; ça ne prouve pas que je ne sais rien » — deux minutes de respiration lente, pieds au sol, question 18 accessible, puis retour à la 17.',
    related: ['simulation-examen', 'demarrage-10-minutes', 'journee-minimale'],
    source: 'Source V2 — §6 Bibliothèque, p. 31',
  },
];
