import type { Method } from '../types';

/** Structurer et représenter : hiérarchie, chaînes, contrastes, frises. Source V2, §6. */
export const structurerMethods: Method[] = [
  {
    id: 'chunking',
    title: 'Chunking / Hiérarchisation',
    subtitle: 'Structure · Charge cognitive',
    summary:
      'Quand il y a trop d’éléments, dégage d’abord 3 à 7 grandes catégories, classe les détails dessous, et rappelle la structure avant les items isolés.',
    categories: ['structurer', 'comprendre'],
    subjects: [],
    infoTypes: ['liste-non-ordonnee', 'tableau', 'texte'],
    problems: ['oublie', 'comprends-pas'],
    aliases: [
      'chunking',
      'regrouper',
      'hiérarchie',
      'hiérarchisation',
      'catégories',
      'trop d’informations',
      'trop de choses à retenir',
    ],
    keywords: ['structure', 'organisation', 'branches', 'invariants', 'exceptions', 'charge cognitive'],
    tags: ['structure d’abord'],
    whenToUse: [
      'Quand il y a beaucoup d’éléments et que tu dois d’abord comprendre la hiérarchie.',
    ],
    avoid: [
      'N’invente pas des catégories qui n’existent pas dans le cours : la structure doit rester fidèle au poly.',
    ],
    quickSteps: [
      'Identifie 3 à 7 grandes catégories.',
      'Classe les détails sous ces branches.',
      'Nomme les invariants et les exceptions.',
      'Rappelle d’abord la structure.',
      'Ajoute progressivement les détails.',
    ],
    procedure: [
      { text: 'Identifier 3 à 7 grandes catégories.' },
      { text: 'Classer les détails sous ces branches.' },
      { text: 'Nommer les invariants et exceptions.', detail: 'Ce qui est toujours vrai structure ; ce qui fait exception se teste à part.' },
      { text: 'Rappeler d’abord la structure.', detail: 'Sans support : les branches avant les feuilles.' },
      { text: 'Ajouter progressivement les détails.' },
    ],
    example:
      'Vingt acides aminés en vrac → 3 familles selon la chaîne latérale, puis les membres de chaque famille, puis les cas particuliers.',
    personal: [
      'Fort levier pour toi : structure d’abord, détails ensuite.',
    ],
    mastery: [
      'Tu peux reconstruire la hiérarchie avant les items isolés.',
    ],
    related: ['mind-map', 'feuille-blanche', 'carte-conceptuelle', 'acronyme'],
    source: 'Source V2 — §6 Bibliothèque, p. 12-13',
    forMe: true,
  },
  {
    id: 'mind-map',
    title: 'Mind map de mémoire',
    subtitle: 'Vue d’ensemble · Relations',
    summary:
      'Une carte mentale construite support fermé, pour tester la hiérarchie et les relations d’un chapitre. Faite en copiant le cours, ce n’est plus un test — c’est de la décoration.',
    categories: ['structurer', 'representer', 'se-tester'],
    subjects: [],
    infoTypes: ['texte', 'liste-non-ordonnee', 'tableau'],
    problems: ['oublie', 'verifier-maitrise', 'comprends-pas'],
    aliases: ['mind map', 'mindmap', 'carte mentale', 'mind mapping', 'vue d’ensemble', 'schéma en branches'],
    keywords: ['hiérarchie', 'branches', 'relations', 'global', 'chapitre'],
    tags: ['vue d’ensemble'],
    whenToUse: [
      'Pour représenter hiérarchie, relations et vue globale d’un chapitre.',
    ],
    avoid: [
      'Une mind map esthétique copiée du cours est de la prise de notes, pas un test.',
    ],
    quickSteps: [
      'Ferme ou réduis le support.',
      'Place le concept central.',
      'Limite les branches principales.',
      'Ajoute seulement relations et mots discriminants.',
      'Compare au poly.',
      'Utilise la carte pour répondre à des questions.',
    ],
    procedure: [
      { text: 'Fermer ou réduire le support.' },
      { text: 'Mettre le concept central.' },
      { text: 'Limiter les branches principales.', detail: '3 à 7 branches : au-delà, la hiérarchie se dilue.' },
      { text: 'Ajouter seulement relations et mots discriminants.', detail: 'Pas de phrases entières : des mots qui tranchent.' },
      { text: 'Comparer au poly.' },
      { text: 'Utiliser la map pour répondre à des questions.' },
    ],
    personal: [
      'Bonne pour exploiter ta structuration ; évite d’y passer du temps graphique.',
    ],
    mastery: [
      'La carte peut être reconstruite et sert de support à des réponses, pas de décoration.',
    ],
    limits: [
      'Utile pour la vue d’ensemble et les relations ; mauvaise si décorative et copiée.',
    ],
    related: ['chunking', 'carte-conceptuelle', 'feuille-blanche'],
    source: 'Source V2 — §6 Bibliothèque, p. 13',
  },
  {
    id: 'carte-conceptuelle',
    title: 'Carte conceptuelle',
    subtitle: 'Relations · Concepts',
    summary:
      'Relie chaque paire de concepts par un verbe précis (« active », « inhibe », « mesure »…). Chaque flèche doit pouvoir se lire comme une phrase scientifique correcte.',
    categories: ['structurer', 'representer', 'comprendre'],
    subjects: ['sante-publique', 'shs', 'biocell'],
    infoTypes: ['mecanisme', 'texte', 'experience'],
    problems: ['comprends-pas', 'melange'],
    aliases: ['carte conceptuelle', 'concept map', 'relations entre notions', 'réseau de concepts'],
    keywords: ['relations', 'verbes', 'liens', 'causalité', 'conditions'],
    tags: ['relations'],
    whenToUse: [
      'Quand la relation entre concepts importe plus qu’une hiérarchie radiale.',
    ],
    avoid: [
      'Ne multiplie pas des flèches sans préciser le sens de la relation : une flèche muette n’apprend rien.',
    ],
    quickSteps: [
      'Liste les concepts clés.',
      'Relie chaque paire pertinente par un verbe précis.',
      'Ajoute conditions et causalités.',
      'Retire les relations redondantes.',
      'Reconstruis à froid.',
    ],
    procedure: [
      { text: 'Lister les concepts clés.' },
      { text: 'Relier chaque paire pertinente par un verbe précis.', detail: '« active », « inhibe », « transporte », « précède », « mesure »…' },
      { text: 'Ajouter conditions / causalités.' },
      { text: 'Retirer les relations redondantes.' },
      { text: 'Reconstruire à froid.' },
    ],
    mastery: [
      'Chaque flèche peut être lue comme une phrase scientifique correcte.',
    ],
    related: ['mind-map', 'chaine-causale', 'double-representation'],
    source: 'Source V2 — §6 Bibliothèque, p. 13-14',
  },
  {
    id: 'chaine-causale',
    title: 'Chaîne causale',
    subtitle: 'Mécanisme · Biocell · Biochimie',
    summary:
      'Pour toute voie ou cascade : état initial → déclencheur → intermédiaires ordonnés → conséquence → résultat. Chaque flèche a une raison, et la logique s’apprend avant les noms.',
    categories: ['structurer', 'comprendre', 'representer'],
    subjects: ['biocell', 'biochimie', 'medicament'],
    infoTypes: ['mecanisme'],
    problems: ['comprends-pas', 'oublie', 'melange'],
    aliases: [
      'chaîne causale',
      'chaine causale',
      'mécanisme',
      'mecanisme',
      'voie',
      'cascade',
      'signalisation',
      'activation',
      'inhibition',
      'cause conséquence',
      'voie de signalisation',
    ],
    keywords: ['déclencheur', 'intermédiaires', 'phosphorylation', 'régulation', 'protéines', 'transduction'],
    tags: ['mécanisme'],
    whenToUse: [
      'Pour une voie, une signalisation, une régulation ou toute relation cause → conséquence.',
    ],
    avoid: [
      'Ne confonds pas ordre et causalité : chaque flèche doit avoir une raison, pas seulement une position.',
    ],
    quickSteps: [
      'Définis l’état initial.',
      'Identifie le déclencheur.',
      'Place les intermédiaires dans l’ordre.',
      'Nomme le type de chaque relation : active, inhibe, transporte, phosphoryle…',
      'Définis la conséquence et le résultat.',
      'Perturbe une étape.',
    ],
    procedure: [
      { text: 'Définir l’état initial.', detail: 'Où en est le système avant que rien ne se passe ? Quel compartiment, quel état ?' },
      { text: 'Identifier le déclencheur.' },
      { text: 'Placer les intermédiaires dans l’ordre.', detail: 'D’abord la logique de la chaîne, ensuite seulement les noms exacts.' },
      { text: 'Nommer le type de relation : active, inhibe, transporte, phosphoryle…' },
      { text: 'Définir la conséquence et le résultat.' },
      { text: 'Perturber une étape.', detail: 'Acteur absent, bloqué, surexprimé : que devient la sortie ? (voir Perturbations « si… alors… »)' },
    ],
    example:
      'Voie de signalisation : ligand → récepteur → protéine relais → effecteur → réponse cellulaire. La logique d’abord, puis les noms exacts de chaque acteur, testés séparément.',
    personal: [
      'Sépare la logique des étiquettes : tu peux bien retenir la chaîne tout en mélangeant les noms. Reteste les noms exacts à distance.',
    ],
    anki: {
      yes: ['Les étiquettes fragiles : noms exacts des intermédiaires, couples acteur-fonction (cartes de contraste si deux voies se ressemblent).'],
      no: ['La chaîne entière : sa logique se reteste en feuille blanche et en perturbations.'],
    },
    mastery: [
      'Tu peux expliquer chaque transition et prédire un blocage.',
    ],
    related: ['perturbations', 'tableau-contraste', 'feynman', 'reconstruction-schema', 'carte-contraste'],
    source: 'Source V2 — §6 Bibliothèque, p. 14',
    forMe: true,
  },
  {
    id: 'perturbations',
    title: 'Perturbation « si… alors… »',
    subtitle: 'Transfert · Mécanisme',
    summary:
      'Supprime, bloque ou amplifie un acteur de la chaîne et prédis la conséquence. Si tu ne peux prédire qu’en récitant tout, la chaîne est apprise comme une poésie.',
    categories: ['appliquer', 'se-tester', 'comprendre'],
    subjects: ['biocell', 'biochimie', 'biophysique', 'medicament'],
    infoTypes: ['mecanisme', 'experience'],
    problems: ['verifier-maitrise', 'applique-pas', 'comprends-pas'],
    aliases: [
      'perturbation',
      'perturbations',
      'si alors',
      'si x manque',
      'si inhibé',
      'si augmente',
      'et si on bloque',
      'transfert mécanisme',
    ],
    keywords: ['prédiction', 'blocage', 'knockout', 'conséquence', 'transfert'],
    tags: ['transfert'],
    whenToUse: [
      'Après avoir compris une chaîne, pour vérifier qu’elle n’est pas récitée comme une poésie.',
    ],
    avoid: [
      'N’invente pas des perturbations nécessitant des connaissances hors poly.',
    ],
    quickSteps: [
      'Choisis un acteur ou une variable.',
      'Supprime-le, inhibe-le, augmente-le ou change son compartiment.',
      'Prédis la conséquence immédiate.',
      'Puis la conséquence secondaire.',
      'Compare au modèle.',
    ],
    procedure: [
      { text: 'Choisir un acteur ou une variable.' },
      { text: 'Le supprimer, l’inhiber, l’augmenter ou changer son compartiment selon le cours.' },
      { text: 'Prédire la conséquence immédiate.' },
      { text: 'Puis la conséquence secondaire.' },
      { text: 'Comparer au modèle.' },
    ],
    example:
      '« Si cette kinase est inhibée, que devient la réponse en aval ? » — réponse attendue sans réciter la voie entière.',
    mastery: [
      'Tu peux prédire sans réciter toute la chaîne.',
    ],
    related: ['chaine-causale', 'auto-explication', 'variation', 'qcm-actif'],
    source: 'Source V2 — §6 Bibliothèque, p. 14-15',
  },
  {
    id: 'tableau-contraste',
    title: 'Tableau de contraste A/B',
    subtitle: 'Discrimination · Anti-confusion',
    summary:
      'Dès que deux notions se mélangent : mets-les côte à côte, choisis 3 à 6 dimensions qui les distinguent, identifie le « discriminant roi », puis alterne des questions A/B.',
    categories: ['structurer', 'corriger', 'se-tester'],
    subjects: ['biocell', 'biochimie', 'medicament', 'sante-publique', 'histologie'],
    infoTypes: ['notions-proches', 'tableau'],
    problems: ['melange'],
    aliases: [
      'je confonds',
      'je mélange',
      'je melange',
      'a vs b',
      'a/b',
      'anti confusion',
      'anti-confusion',
      'discriminant',
      'deux notions proches',
      'tableau comparatif',
      'protéines proches',
      'interférence',
      'différence entre',
    ],
    keywords: ['contraste', 'comparaison', 'dimensions', 'discriminant roi', 'confusion'],
    tags: ['anti-confusion', 'prioritaire'],
    whenToUse: [
      'Dès que deux notions, molécules, voies, modèles ou structures commencent à se mélanger.',
    ],
    avoid: [
      'Ne fais pas un tableau de 20 lignes : garde uniquement les dimensions qui discriminent.',
    ],
    quickSteps: [
      'Mets A et B côte à côte.',
      'Choisis 3 à 6 dimensions discriminantes.',
      'Identifie le « discriminant roi ».',
      'Produis A puis B sans support.',
      'Alterne des questions A/B.',
      'Crée éventuellement une carte de contraste.',
    ],
    procedure: [
      { text: 'Mettre A et B côte à côte.', detail: 'Arrête l’apprentissage séparé : c’est la comparaison directe qui désamorce l’interférence.' },
      { text: 'Choisir 3 à 6 dimensions discriminantes.' },
      { text: 'Identifier le « discriminant roi ».', detail: 'LE critère qui tranche à coup sûr, celui que tu vérifieras en premier en QCM.' },
      { text: 'Produire A puis B sans support.' },
      { text: 'Alterner des questions A/B.' },
      { text: 'Créer éventuellement une carte de contraste.', detail: 'Une carte Anki qui teste le critère qui tranche (voir Carte piège / contraste).' },
    ],
    example:
      'Deux protéines de voies voisines qui se mélangent : tableau à 4 lignes (localisation, activateur, cible, effet), discriminant roi = la cible, puis questions alternées.',
    personal: [
      'Prioritaire pour toi à cause de l’interférence observée entre noms de mécanismes proches.',
    ],
    anki: {
      yes: ['Le discriminant roi sous forme de carte piège / contraste.'],
      no: ['Le tableau entier recopié dans une seule carte.'],
    },
    mastery: [
      'Tu peux justifier rapidement pourquoi un item est A et pas B.',
    ],
    related: ['carte-contraste', 'interleaving', 'chaine-causale', 'qcm-actif'],
    source: 'Source V2 — §6 Bibliothèque, p. 15',
    forMe: true,
  },
  {
    id: 'frise-chronologique',
    title: 'Frise chronologique',
    subtitle: 'Séquence · Embryologie · Processus',
    summary:
      'Quand l’ordre et les transformations comptent : place les événements, écris « ce qui change » sur chaque flèche, reconstruis de mémoire, puis teste une inversion.',
    categories: ['structurer', 'representer', 'memoriser'],
    subjects: ['embryologie', 'histologie', 'biocell'],
    infoTypes: ['chronologie', 'liste-ordonnee'],
    problems: ['oublie', 'melange'],
    aliases: ['frise', 'frise chronologique', 'chronologie', 'ordre', 'timeline', 'avant après', 'étapes dans l’ordre'],
    keywords: ['séquence', 'transformation', 'stades', 'étapes', 'temps'],
    tags: ['séquence'],
    whenToUse: [
      'Quand l’ordre et les transformations temporelles comptent.',
    ],
    avoid: [
      'Ne mémorise pas seulement des dates sans comprendre ce qui change entre les étapes.',
    ],
    quickSteps: [
      'Place l’état initial.',
      'Ajoute les événements majeurs.',
      'Écris « ce qui change » sur chaque flèche.',
      'Relie chaque transformation à son résultat.',
      'Reconstruis de mémoire.',
      'Teste une inversion ou un décalage.',
    ],
    procedure: [
      { text: 'Placer l’état initial.' },
      { text: 'Ajouter les événements majeurs.' },
      { text: 'Pour chaque flèche écrire « ce qui change ».', detail: 'La flèche porte la transformation, pas seulement l’ordre.' },
      { text: 'Relier chaque transformation à son résultat.' },
      { text: 'Reconstruire de mémoire.' },
      { text: 'Tester une inversion ou un décalage.', detail: '« Que se passe-t-il si cette étape est retardée ? » — le test de compréhension de la séquence.' },
    ],
    example:
      'Semaine de développement embryonnaire : chaque flèche porte la transformation (« se creuse », « migre », « fusionne »), pas juste un numéro de jour.',
    personal: [
      'Ton ordre immédiat est bon ; le défi est la rétention différée des détails, donc re-teste la frise à distance.',
    ],
    anki: {
      yes: ['Dates, dérivés, noms et associations arbitraires accrochés à la frise.'],
      no: ['La frise entière dans une seule carte.'],
    },
    mastery: [
      'Tu peux reconstruire l’ordre et expliquer les transformations.',
    ],
    related: ['histoire-chainage', 'reconstruction-schema', 'rappel-differe', 'chaine-causale'],
    source: 'Source V2 — §6 Bibliothèque, p. 15-16',
  },
  {
    id: 'double-representation',
    title: 'Double représentation : mots + schéma',
    subtitle: 'Représentation · Compréhension',
    summary:
      'Écris l’idée en une phrase ET dessine la relation en schéma minimal. Masque l’un, reconstruis l’autre : chaque format doit pouvoir régénérer l’autre.',
    categories: ['representer', 'comprendre'],
    subjects: ['biophysique', 'physique', 'biocell'],
    infoTypes: ['mecanisme', 'schema', 'formule'],
    problems: ['comprends-pas', 'oublie'],
    aliases: ['dual coding', 'double codage', 'mots plus schéma', 'mots et schéma', 'diagramme', 'texte et dessin'],
    keywords: ['représentation', 'verbal', 'spatial', 'schéma minimal'],
    tags: ['double codage'],
    whenToUse: [
      'Quand une information possède à la fois une structure verbale et spatiale/causale.',
    ],
    avoid: [
      'N’ajoute pas une image décorative qui n’apporte aucune relation utile.',
    ],
    quickSteps: [
      'Écris l’idée en une phrase.',
      'Construis un schéma minimal qui montre la relation.',
      'Aligne les mêmes concepts dans les deux formats.',
      'Masque l’un et reconstruis l’autre.',
      'Teste sur une formulation nouvelle.',
    ],
    procedure: [
      { text: 'Écrire l’idée en une phrase.' },
      { text: 'Construire un schéma minimal qui montre la relation.' },
      { text: 'Aligner les mêmes concepts dans les deux formats.' },
      { text: 'Masquer l’un et reconstruire l’autre.' },
      { text: 'Tester sur une formulation nouvelle.' },
    ],
    mastery: [
      'Chaque représentation peut reconstruire l’autre.',
    ],
    related: ['reconstruction-schema', 'carte-conceptuelle', 'chaine-causale'],
    source: 'Source V2 — §6 Bibliothèque, p. 19',
  },
];
