/**
 * Punchlines du mode Déclic — courtes, sèches, deuxième personne.
 * Écrites pour l'app (voix d'Axel) : jamais de fausse attribution,
 * dures sur l'action, jamais sur la personne. Une ligne = une claque utile.
 * Servies sur le hub Motivation (« Une autre »), en pied des discours,
 * et disponibles dans le flux via le thème courage.
 */

export const PUNCHLINES: string[] = [
  // ------------------------------------------------------------- démarrage
  'T’as pas besoin d’envie. T’as besoin de dix minutes.',
  'Pendant que tu hésites, quelqu’un d’autre fait des QCM.',
  'La motivation arrive après le début. Jamais avant. Commence.',
  'Le meilleur moment, c’était ce matin. Le deuxième meilleur, c’est maintenant.',
  'Tu ne trouveras pas l’envie en scrollant. Elle est dans le poly.',
  '« Bientôt » n’est pas une heure. Choisis-en une vraie.',
  'Une page. Maintenant. On négociera après.',
  'Ce que tu repousses à ce soir, tu le repousseras à demain. Tue la boucle.',
  'Commencer moche bat attendre parfait. Tous les jours.',
  'Trois minutes de courage. Le reste roule tout seul.',
  'Ta flemme ne survit jamais à un minuteur lancé.',
  'Le démarrage est un muscle. Chaque « maintenant » le renforce.',
  'Tu réfléchis à ta session au lieu de la faire. Inverse.',
  'L’élan ne se trouve pas. Il se fabrique — premier geste, tout de suite.',
  'Décide en une seconde, exécute en dix minutes, fier·e toute la soirée.',
  // ------------------------------------------------------------ discipline
  'Le concours ne compte pas tes intentions. Il compte tes rappels.',
  'Personne ne viendra le faire à ta place. C’est une bonne nouvelle : tu es là.',
  'La régularité bat le talent qui dort. Encore aujourd’hui.',
  'Fais-le fatigué·e. Fais-le sans envie. Fais-le petit. Mais fais-le.',
  'Tu n’as pas à finir aujourd’hui. Tu as à ne pas t’arrêter.',
  'Une heure nette vaut trois heures molles. Coupe le téléphone.',
  'Ce n’est pas une question de temps. Tu as le temps. C’est une question de démarrage.',
  'Les grands classements sont faits de petites soirées comme celle-là.',
  'Ta chaise ne compte pas les heures. Ton cerveau compte les rappels.',
  'Chaque unité validée est un vote pour la personne que tu deviens.',
  'Le programme n’attend pas. Toi non plus.',
  'Un jour à 10 % vaut infiniment plus qu’un jour à zéro.',
  'La discipline, c’est se parler en chef, pas en victime.',
  'Range le théâtre des excuses. La scène, c’est ton bureau.',
  'Tu veux un secret ? Il n’y en a pas. Rappels, espacement, sommeil. Tous les jours.',
  // ------------------------------------------------------------- l’enjeu
  'C’est cette année que ça se joue. Pas l’année prochaine. Celle-là.',
  'Janvier ne te demandera pas si tu avais envie en novembre.',
  'Ta place existe déjà. Quelqu’un la prendra. Autant que ce soit toi.',
  'Chaque soirée est un bulletin de vote. Tu votes pour qui, là ?',
  'Le concours se gagne les jours où tu n’avais pas envie.',
  'Dans un an, tu voudras pouvoir dire « j’ai tout donné ». Ça s’écrit ce soir.',
  'Les jours faciles ne classent personne. C’est aujourd’hui que tu doubles des gens.',
  'Ce que tu fais quand personne ne regarde — c’est exactement ça, ton classement.',
  'La minute que tu perds ne crie pas. Elle s’additionne en silence.',
  'Tu n’affrontes pas les autres. Tu affrontes ta version d’hier. Bats-la.',
  '« J’aurais pu » pèse plus lourd que tous les polys réunis. Évite-toi cette phrase.',
  'Le futur toi de janvier te regarde. Rends-le fier.',
  'Une année dure, dix mois. Une carrière de soignant, quarante ans. Bon échange.',
  'Chaque cascade apprise, c’est un patient mieux soigné un jour. Rien n’est gratuit.',
  // ---------------------------------------------------------- le téléphone
  'Ton téléphone a des milliers d’ingénieurs. Toi, tu as une autre pièce. Utilise-la.',
  'Chaque déverrouillage coûte dix minutes de fil perdu. Fais le calcul.',
  'Le scroll ne repose pas. Il vole. Nuance importante.',
  'Personne n’a jamais progressé au classement depuis son écran de veille.',
  'Pose-le loin. La volonté est nulle en combat rapproché, la distance est imbattable.',
  'Tu regardes la vie des autres pendant que la tienne attend sur le bureau.',
  '« Juste cinq minutes » est le plus vieux mensonge du monde. Tu le sais.',
  'L’attention est ta seule vraie monnaie cette année. Arrête de la donner gratuitement.',
  // ------------------------------------------------------------- l’échec
  'Une note ratée analysée vaut mieux qu’une réussie par chance.',
  'Rate. Analyse. Corrige. Reviens. C’est la seule boucle qui monte.',
  'Ton rang d’aujourd’hui est la photo d’hier. La photo de demain se prend ce soir.',
  'Ruminer coûte des heures et rapporte zéro point. Corrige par cause, puis avance.',
  'Les majors ont pris des claques. Ils les ont disséquées. C’est toute la différence.',
  'Chaque erreur a une cause. Chaque cause a un remède. Au travail.',
  'Tomber n’est pas le problème. Camper au sol, si.',
  'Ta pire colle contient tes prochains points. Va les chercher.',
  // -------------------------------------------------------------- le doute
  'Le doute ne se discute pas. Il se contredit — par une preuve, maintenant.',
  'Pendant que tu te compares, ta propre courbe t’attend. Fais-la monter.',
  'Personne n’est « fait pour ça ». Il y a ceux qui construisent, c’est tout.',
  'À la BU, tout le monde a l’air sûr. Tout le monde doute. Bosse.',
  'Tu n’as pas besoin de te sentir capable. Tu as besoin de faire l’unité suivante.',
  'L’imposteur n’est pas celui qui doute. C’est celui qui n’essaie plus.',
  'Ta légitimité ne se vote pas. Elle se construit, rappel par rappel.',
  'Les impressions mentent. Les rappels réussis, jamais.',
  // ------------------------------------------------------------- l’énergie
  'Fatigué·e ? Version minimale. Mais version. Jamais zéro.',
  'Le sommeil n’est pas une pause du travail. C’est la moitié du travail.',
  'La nuit blanche est le seul investissement à rendement garanti négatif.',
  'Protège ta nuit comme tu protèges tes points. C’est la même chose.',
  'Un cerveau reposé retient double. Dormir tôt est un acte de compétition.',
  'L’endurance bat l’héroïsme. Sur dix mois, toujours.',
  'Tu n’es pas une machine. Mais ta routine peut en être une. Appuie-toi dessus.',
  // ------------------------------------------------------------- l’action
  'Moins de plans, plus de rappels.',
  'La to-do parfaite d’une soirée perdue reste une soirée perdue.',
  'Organiser n’est pas travailler. Trois lignes suffisent. Puis exécute.',
  'Relire caresse le cours. Se tester le grave. Choisis ce qui rapporte.',
  'Ferme le cours. Ce qui sort de ta tête est à toi. Le reste est une illusion.',
  'Le surligneur ne mémorise rien. Ta main sur une feuille blanche, si.',
  'Une question posée vaut dix pages relues.',
  'Ce qui se mesure progresse. Compte tes unités, pas tes heures.',
  'La méthode n’est pas un détail. C’est l’écart entre deux étudiants qui bossent autant.',
  'Simple, régulier, actif. Le reste est de la décoration.',
  // ------------------------------------------------------------- le moment
  'Gagne ta matinée, tu gagnes ta journée.',
  'La première heure du jour donne le ton des douze suivantes.',
  'Le soir appartient à ceux qui scellent leur journée au lieu de la fuir.',
  'Dix minutes de rappel avant de dormir, et ta nuit bosse pour toi.',
  'Chaque « demain » que tu dis en cache un autre. Dis « maintenant » une fois.',
  'L’heure parfaite n’existe pas. L’heure actuelle, si.',
  'Aujourd’hui compte double : c’est le seul jour où tu peux agir.',
  // ------------------------------------------------------------- le retour
  'Revenir, c’est la compétence. Zéro pause n’existe pas ; zéro abandon, si.',
  'Le retour parfait n’existe pas. Le retour immédiat, si. Choisis-le.',
  'Une pause devient une pente le jour où tu ne reviens pas. Reviens aujourd’hui.',
  'On ne rattrape pas une semaine en un soir. On la rattrape en ne perdant plus un jour.',
  'La culpabilité ne porte pas de stylo. Pose-la, prends le tien.',
  'Le cours du jour d’abord. Toujours. Le retard attendra son tri.',
  'Chaque champion s’est arrêté un jour. Aucun n’est resté arrêté.',
  // ------------------------------------------------------------- la force
  'Tu as déjà survécu à toutes tes pires semaines. Celle-là aussi.',
  'Tu es allé·e trop loin pour ne pas aller au bout.',
  'La version de toi qui réussit fait exactement ce que tu hésites à faire là.',
  'Ton avenir ne se décide pas en juin. Il se décide dans des minutes comme celle-ci.',
  'Sois exigeant·e avec l’action, doux·ce avec la personne. Dans cet ordre.',
  'Personne ne t’a promis facile. On t’a promis possible. C’est suffisant.',
  'Le courage, ce soir, ressemble à un poly ouvert. C’est tout. C’est énorme.',
  'Tu n’es pas fatigué·e de travailler. Tu es fatigué·e de lutter contre toi. Alors arrête de lutter : commence.',
  'Un jour, ce sera toi qu’on appellera en garde. Prépare cette personne.',
  'Fais simple : la prochaine unité. Fais vite : maintenant. Fais vrai : cours fermé.',
  'Là, tout de suite, tu as exactement ce qu’il faut : un cours, dix minutes, et toi.',
  'Arrête de lire des punchlines. Tu sais ce qu’il te reste à faire.',
];
