import type { Subject } from './types';

/**
 * Méthodes par matière — protocoles complets de la Source V2, §5 (p. 6-8).
 * Chaque étape renvoie vers les fiches méthodes concernées.
 */
export const SUBJECTS: Subject[] = [
  {
    id: 'biocell',
    name: 'Biologie cellulaire',
    short: 'Biocell',
    intro:
      'Des mécanismes, des compartiments, des voies qui se ressemblent : la logique d’abord, les noms exacts ensuite, et un contraste A/B dès que deux voies se mélangent.',
    protocol: [
      { text: 'Film sans les noms : où commence le processus, quel signal, quel but ?' },
      { text: 'Carte des compartiments : extérieur, membrane, cytoplasme, organites, noyau selon le cours.' },
      { text: 'Chaîne : entrée → acteurs → ordre → sortie → lieu.' },
      { text: 'Ajouter les noms exacts seulement après la logique.' },
      { text: 'Fermer et redessiner ; expliquer pourquoi chaque transition a lieu.' },
      { text: 'Perturber : acteur absent, bloqué, changé de compartiment ou de phase.' },
      { text: 'Comparer les voies proches ; créer des cartes de contraste pour les étiquettes fragiles.' },
      { text: 'Image occlusion si la position porte une information.' },
    ],
    methods: [
      'chaine-causale',
      'perturbations',
      'reconstruction-schema',
      'tableau-contraste',
      'carte-contraste',
      'imagerie-interactive',
      'image-occlusion',
      'feuille-blanche',
    ],
    aliases: ['biocell', 'bio cell', 'biologie cellulaire', 'cellule', 'organites', 'voies cellulaires'],
    source: 'Source V2 — §5 Méthodes par matière, p. 6',
  },
  {
    id: 'biochimie',
    name: 'Biochimie',
    short: 'Biochimie',
    intro:
      'Relier structure, fonction, localisation, mécanisme et régulation — et ne jamais apprendre une voie comme une poésie : la carte globale d’abord, puis les flux, puis les détails ciblés dans Anki.',
    protocol: [
      { text: 'Relier structure / molécule → fonction → localisation → mécanisme → régulation.' },
      { text: 'Construire la carte globale avant les détails.' },
      { text: 'Dessiner les voies et les flux ; ne pas apprendre une voie comme une poésie.' },
      { text: 'Tester le sens inverse : conséquence → mécanisme possible.' },
      { text: 'Perturber une étape ou une régulation.' },
      { text: 'Comparer les molécules proches dans un tableau de contraste.' },
      { text: 'Anki pour localisation, fonction, cofacteur, régulateur, exception et détails discriminants.' },
    ],
    methods: [
      'chaine-causale',
      'chunking',
      'perturbations',
      'tableau-contraste',
      'carte-contraste',
      'repetition-espacee',
      'carte-qr',
      'feuille-blanche',
    ],
    aliases: ['biochimie', 'bioch', 'métabolisme', 'enzymes', 'protéines', 'proteines', 'voies métaboliques'],
    source: 'Source V2 — §5 Méthodes par matière, p. 6',
  },
  {
    id: 'chimie',
    name: 'Chimie',
    short: 'Chimie',
    intro:
      'Grandeurs, unités, lois et conditions avant les formules — puis la montée en autonomie : exemple résolu, complétion, exercice à froid, variation, séries mélangées.',
    protocol: [
      { text: 'Carte des grandeurs, unités, lois et conditions avant les formules.' },
      { text: 'Exemple entièrement résolu en expliquant le choix de chaque étape.' },
      { text: 'Exemple à compléter / fading.' },
      { text: 'Exercice à froid sans formule visible.' },
      { text: 'Variation : données, inconnue, formulation ou unité changée.' },
      { text: 'Séries mélangées pour apprendre à choisir le modèle.' },
      { text: 'Contrôle dimensionnel, signe et ordre de grandeur.' },
    ],
    methods: [
      'exemple-resolu',
      'fading',
      'exercice-a-froid',
      'variation',
      'interleaving',
      'auto-explication',
      'carte-calcul',
    ],
    aliases: ['chimie', 'réactions', 'moles', 'concentration', 'équilibres', 'ph'],
    source: 'Source V2 — §5 Méthodes par matière, p. 7',
  },
  {
    id: 'physique',
    name: 'Physique',
    short: 'Physique',
    intro:
      'Système, référentiel, schéma, axes et conventions avant toute équation ; prédire qualitativement, poser le modèle et ses hypothèses, puis retirer l’aide jusqu’au mélange de problèmes.',
    protocol: [
      { text: 'Système → référentiel → schéma → axes → conventions de signe.' },
      { text: 'Prédiction qualitative avant toute équation.' },
      { text: 'Modèle et hypothèses avant la formule.' },
      { text: 'Exemple → complétion → froid → variation.' },
      { text: 'Contrôle dimensionnel, cas limites, ordre de grandeur.' },
      { text: 'Mélange de problèmes pour choisir la méthode, pas seulement exécuter.' },
    ],
    methods: [
      'exemple-resolu',
      'fading',
      'exercice-a-froid',
      'variation',
      'interleaving',
      'auto-explication',
      'carte-calcul',
      'double-representation',
    ],
    aliases: ['physique', 'mécanique', 'formule physique', 'exo physique', 'unités', 'newton', 'ondes'],
    source: 'Source V2 — §5 Méthodes par matière, p. 7',
  },
  {
    id: 'biophysique',
    name: 'Biophysique',
    short: 'Biophysique',
    intro:
      'Du phénomène biologique au modèle physique : hypothèses, grandeurs, équation — prédire le sens du résultat avant de calculer, puis interpréter biologiquement.',
    protocol: [
      { text: 'Phénomène biologique → modèle physique → hypothèses → grandeurs → équation.' },
      { text: 'Prédire le sens du résultat avant calcul.' },
      { text: 'Exemple guidé puis retrait progressif de l’aide.' },
      { text: 'Interpréter le résultat biologiquement.' },
      { text: 'QCM conceptuels sans calcul pour vérifier le modèle mental.' },
      { text: 'Tableau conditions / conséquences pour les modèles proches.' },
    ],
    methods: [
      'exemple-resolu',
      'fading',
      'exercice-a-froid',
      'double-representation',
      'tableau-contraste',
      'qcm-actif',
      'auto-explication',
    ],
    aliases: ['biophysique', 'biophy', 'compartiments liquidiens', 'membranes', 'pression osmotique', 'rayonnements'],
    source: 'Source V2 — §5 Méthodes par matière, p. 7',
  },
  {
    id: 'biostats',
    name: 'Biostatistiques',
    short: 'Biostats',
    intro:
      'Le vrai jeu : passer de la question posée au bon outil. Variables, données, conditions, test — chaque décision nommée, chaque résultat conclu par une phrase d’interprétation.',
    protocol: [
      { text: 'Question posée → type de variables → données → conditions → outil / test.' },
      { text: 'Exemple où chaque décision statistique est nommée.' },
      { text: 'Exercice à froid puis séries mélangées.' },
      { text: 'Expliquer pourquoi les autres méthodes ne conviennent pas.' },
      { text: 'Toujours terminer par une phrase d’interprétation.' },
      { text: 'Anki pour hypothèses, définitions, interprétations et formules contextualisées.' },
    ],
    methods: [
      'exemple-resolu',
      'exercice-a-froid',
      'interleaving',
      'auto-explication',
      'carte-qr',
      'carte-calcul',
    ],
    aliases: ['biostatistiques', 'biostats', 'stats', 'statistiques', 'tests statistiques', 'p-value', 'variables'],
    source: 'Source V2 — §5 Méthodes par matière, p. 7',
  },
  {
    id: 'anatomie',
    name: 'Anatomie',
    short: 'Anatomie',
    intro:
      'Orienter, poser les gros repères, puis les rapports et trajets — reconstruire de mémoire même grossièrement, et ne jamais apprendre une seule planche.',
    protocol: [
      { text: 'Orienter : plan, droite / gauche, supérieur / inférieur, antérieur / postérieur.' },
      { text: 'Apprendre les gros repères avant les petites structures.' },
      { text: 'Ajouter rapports, trajet et critères discriminants.' },
      { text: 'Reconstruire de mémoire, même grossièrement.' },
      { text: 'Changer de vue ; ne jamais apprendre une seule planche.' },
      { text: 'Image occlusion + questions relationnelles.' },
    ],
    methods: [
      'reconstruction-schema',
      'image-occlusion',
      'chunking',
      'imagerie-interactive',
      'palais-mental',
      'rappel-differe',
    ],
    aliases: ['anatomie', 'anat', 'planche', 'coupes', 'repères anatomiques', 'membre', 'squelette'],
    source: 'Source V2 — §5 Méthodes par matière, p. 7',
  },
  {
    id: 'histologie',
    name: 'Histologie',
    short: 'Histologie',
    intro:
      'Du faible au fort grossissement : architecture puis critères discriminants, décrire sans légendes (« pourquoi A et pas B ? »), varier les images, chronométrer les QCM visuels.',
    protocol: [
      { text: 'Faible grossissement : architecture générale et orientation.' },
      { text: 'Fort grossissement : cellules et critères discriminants.' },
      { text: 'Décrire sans légendes : « pourquoi A et pas B ? ».' },
      { text: 'Varier image, zoom, recadrage et orientation.' },
      { text: 'Image occlusion + carte du critère de reconnaissance.' },
      { text: 'QCM visuels chronométrés.' },
    ],
    methods: [
      'reconstruction-schema',
      'tableau-contraste',
      'image-occlusion',
      'carte-contraste',
      'qcm-actif',
      'rappel-differe',
    ],
    aliases: ['histologie', 'histo', 'lame', 'planche histo', 'tissus', 'microscope', 'coloration', 'histo image'],
    source: 'Source V2 — §5 Méthodes par matière, p. 7-8',
  },
  {
    id: 'embryologie',
    name: 'Embryologie',
    short: 'Embryologie',
    intro:
      'Un chapitre = un film : avant → événement → transformation → après. La frise porte les transformations, le redessin teste les transitions, Anki garde les dates et dérivés.',
    protocol: [
      { text: 'Transformer le chapitre en film : avant → événement → transformation → après.' },
      { text: 'Construire une frise et relier chaque étape à ce qu’elle produit.' },
      { text: 'Redessiner les transitions clés.' },
      { text: 'Utiliser l’imagerie de mouvement si elle vient naturellement.' },
      { text: 'Anki pour dates, dérivés, noms et associations arbitraires.' },
      { text: 'Tester l’ordre et les conséquences d’un décalage.' },
    ],
    methods: [
      'frise-chronologique',
      'reconstruction-schema',
      'imagerie-interactive',
      'repetition-espacee',
      'carte-qr',
      'rappel-differe',
    ],
    aliases: ['embryologie', 'embryo', 'développement', 'stades', 'semaines', 'feuillets', 'dérivés'],
    source: 'Source V2 — §5 Méthodes par matière, p. 8',
  },
  {
    id: 'sante-publique',
    name: 'Santé publique',
    short: 'Santé publ.',
    intro:
      'Chaque indicateur se décompose : ce que ça mesure, numérateur, dénominateur, population, période, interprétation — puis exemples / non-exemples et mini-cas pour choisir la mesure.',
    protocol: [
      { text: 'Indicateur = ce que ça mesure + numérateur + dénominateur + population + période + interprétation.' },
      { text: 'Créer exemples et non-exemples.' },
      { text: 'Comparer les termes proches avec un critère décisif.' },
      { text: 'Dessiner les plans d’étude quand utile.' },
      { text: 'Mini-cas pour choisir la mesure.' },
      { text: 'QCM : transformer un item faux en phrase exacte.' },
    ],
    methods: [
      'chunking',
      'tableau-contraste',
      'carte-contraste',
      'liste-questions',
      'qcm-actif',
      'carte-qr',
    ],
    aliases: ['santé publique', 'sante publique', 'épidémiologie', 'epidemiologie', 'incidence', 'prévalence', 'indicateurs'],
    source: 'Source V2 — §5 Méthodes par matière, p. 8',
  },
  {
    id: 'medicament',
    name: 'Initiation au médicament',
    short: 'Médicament',
    intro:
      'Classer chaque médicament (définition → classe/cible → mécanisme → effet → risque → cadre), comparer classes et exceptions, et contrôler les pièges : absolus, négations, inversions cible/effet.',
    protocol: [
      { text: 'Classer : définition → classe / cible → mécanisme → effet → risque → cadre.' },
      { text: 'Comparer classes, cibles, effets et exceptions.' },
      { text: 'Cartes bidirectionnelles seulement si les deux sens sont réellement exigés.' },
      { text: 'QCM rapides et mélangés avec verbalisation du mécanisme.' },
      { text: 'Contrôler absolus, négations et inversions cible / effet.' },
    ],
    methods: [
      'chunking',
      'tableau-contraste',
      'chaine-causale',
      'carte-contraste',
      'qcm-actif',
      'interleaving',
    ],
    aliases: ['médicament', 'medicament', 'pharmaco', 'pharmacologie', 'classes thérapeutiques', 'cible', 'effet indésirable'],
    source: 'Source V2 — §5 Méthodes par matière, p. 8',
  },
  {
    id: 'shs',
    name: 'SHS',
    short: 'SHS',
    intro:
      'Notions, auteurs, cadres et rôle argumentatif : repérer thèse, arguments, limites — construire des plans de 5 minutes, produire des QROC, et préserver les formulations exactes du cours.',
    protocol: [
      { text: 'Identifier notions, auteurs, cadres et rôle argumentatif.' },
      { text: 'Repérer thèse, arguments, limites et exemples.' },
      { text: 'Construire des plans de 5 minutes avant rédaction.' },
      { text: 'Produire des QROC, pas seulement des cartes.' },
      { text: 'Comparer les concepts proches.' },
      { text: 'Préserver les formulations et distinctions du cours.' },
    ],
    methods: [
      'liste-questions',
      'chunking',
      'feuille-blanche',
      'tableau-contraste',
      'carte-qr',
      'feynman',
    ],
    aliases: ['shs', 'sciences humaines', 'sciences humaines et sociales', 'auteurs', 'thèse', 'dissertation', 'qroc'],
    source: 'Source V2 — §5 Méthodes par matière, p. 8',
  },
];

export const SUBJECTS_BY_ID: ReadonlyMap<string, Subject> = new Map(
  SUBJECTS.map((s) => [s.id, s]),
);
